config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  namespace :admin do
    get  'login',  to: 'login#login'   # show page
    post 'login',  to: 'login#create', as: :create_session  # authenticate
    delete 'logout', to: 'login#destroy'

    get '/', to: 'dashboard#index', as: :dashboard
    resources :products
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get '/carrinho', to: 'cart#index', as: :cart
  get  '/endereco', to: 'address#new', as: :new_address
  post '/endereco', to: 'address#create', as: :addresses

  get '/checkout', to: 'checkouts#index'
  post '/checkout', to: 'checkouts#create', as: :checkouts

  get 'produtos', to: 'products#index', as: :products
  get 'produtos/:id', to: 'products#show', as: :product
  get 'pedidos', to: 'orders#index', as: :orders

  post 'pedidos/add/:product_id', to: 'orders#add', as: :add_product
  post 'pedidos/remove/:product_id', to: 'orders#remove', as: :remove_product

  root 'products#index'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :line_items

  enum status: {
    pending: 0,
    paid: 1,
    cancelled: 2,
    cart: 3
  }

  validates :total, numericality: { greater_than_or_equal_to: 0 }

  def recalculate!
    total = line_items.map { |li| li.quantity * li.product.price }.sum
    update!(total: total)
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image

  validates :price, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: {
    user: 0,
    admin: 1,
    editor: 2
  }

  has_many :orders
  has_one :address, dependent: :destroy

  def cart_order
    orders.find_or_create_by(status: :cart)
  end
end

app/controllers/address_controller.rb
class AddressController < ApplicationController
  before_action :authenticate_user!

  def new
    @address = current_user.address || current_user.build_address
  end

  def create
    @address = current_user.build_address(address_params)

    if @address.save
      redirect_to root_path, notice: 'Endereço salvo com sucesso.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def address_params
    params.require(:address).permit(
      :street,
      :number,
      :neighborhood,
      :city,
      :state,
      :zip_code
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout 'application'
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  include Devise::Controllers::Helpers
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index
    @order = current_user.orders.find_or_create_by(status: "cart")
  end
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  before_action :authenticate_user!
  before_action :confirm_address, if: :address_missing?

  def index 
    @order = current_user.cart_order
    @public_key = ENV['MP_PUBLIC_KEY']
  end
  
  def create
    @order = current_user.cart_order

    case params[:payment_method]
    when "card"
      client = MercadoPago::Client.new

      response = client.create_payment(
        transaction_amount: @order.total.to_f,
        token: params[:token],
        description: "Pedido ##{@order.id}",
        installments: 1,
        payment_method_id: 'master',
        payer: {
          email: current_user.email
        }
      )

      if response.code == 201
        @order.paid! 
      end

    when "pix"
      client = MercadoPago::Client.new

   

      response = client.create_payment(
        transaction_amount: @order.total.to_f,
        description: "Pedido ##{@order.id}",
        payment_method_id: "pix",
        payer: {
          email: current_user.email
        }
      )

      if response.code == 201
        qr_code = response['point_of_interaction']['transaction_data']['qr_code']
        qr_code_base64 = response['point_of_interaction']['transaction_data']['qr_code_base64']

        render json: { qr_code: qr_code, qr_code_base64: qr_code_base64 }
      end 
    end
  end 

  private

  def address_missing?
    current_user.present? && current_user.address.nil?
  end



  def confirm_address
    redirect_to new_address_path, alert: "Por favor, cadastre seu endereço antes de continuar."
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  def index

  end

  def add
    product = Product.find(params[:product_id])

    order = current_user.cart_order

    line_item = order.line_items.find_or_initialize_by(product: product)
    line_item.quantity ||= 0
    line_item.quantity += 1
    line_item.save!

    order.recalculate!

    redirect_back fallback_location: root_path
  end

  def remove
    item = current_user.cart_order.line_items.find_by(product_id: params[:product_id])
    return redirect_back(fallback_location: root_path) unless item

    item.quantity -= 1

    if item.quantity <= 0
      item.destroy
    else
      item.save!
    end

    order.recalculate!

    redirect_back fallback_location: root_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end 

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/address_helper.rb
module AddressHelper
end

app/helpers/admin/login_helper.rb
module Admin::LoginHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Ecommerce From Scratch" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Ecommerce From Scratch" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  
    <nav class="navbar">
        <div class="navbar-left">
          <%= link_to "Home", "/", class: "navbar-brand" %>
        </div>

        <div class="navbar-right">
          <%= link_to "Produtos", products_path, class: "navbar-link" %>
          <% if user_signed_in? %>
            <div class="">
              <%= link_to "Meus Pedidos", orders_path, class: "navbar-link" %>
            </div>
          <% end %>
          <%= link_to cart_path, class: "navbar-cart", aria: { label: "Carrinho" } do %>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="22"
              height="22"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <circle cx="9" cy="21" r="1"></circle>
              <circle cx="20" cy="21" r="1"></circle>
              <path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path>
            </svg>
          <% end %>
          <% if user_signed_in? %>
            <%= link_to "Meu Perfil", edit_user_registration_path, class: "navbar-link" %>
          <% else %>
            <%= link_to "Entrar", new_user_session_path, class: "navbar-link" %>
          <% end %>          
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/layouts/auth.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>